In [4]:
import numpy as np
import numpy.linalg
import scipy as sp
import scipy.linalg

In [28]:
#problem 1

c = np.array([[1], [0], [-2], [3]])

d = np.array([[2], [1], [-1], [3]])

print(c+d)

print(c-2*d)

print(2*c + 3*d)
    


[[ 3]
 [ 1]
 [-3]
 [ 6]]
[[-3]
 [-2]
 [ 0]
 [-3]]
[[ 8]
 [ 3]
 [-7]
 [15]]


In [30]:
#problem 2

v = np.array([[3], [2]])

b = np.array([[-1], [4]])

print(2*v+b)

[[5]
 [8]]


In [32]:
#problem 3

In [ ]:
#problem 4

In [ ]:
#problem 5

In [ ]:
#problem 6

In [ ]:
#problem 7 

In [62]:
#problem 8

a = np.array([[1], [2], [3]])

b = np.array([[-2], [0], [5]])

print(np.vdot(a,b))

print(np.cross(a,b, axisa=0, axisb=0))

print(np.linalg.norm(a))

print(np.linalg.norm(b))

13
[[ 10 -11   4]]
3.7416573867739413
5.385164807134504


In [63]:
#problem 9

n = np.array([[1], [3], [-2]])

p = np.array([[1], [2], [3]])



[1] x + [3] y + [-2] z= [-36]


In [ ]:
#problem 10

print(np.array())

In [59]:
#problem 11

n = np.array([[1], [2], [3]])

p = np.array([[2], [3], [1]])

n_magnitude = np.linalg.norm(n)

dot = np.vdot(n,p)

numerator = dot-3

distance = numerator/n_magnitude

print(distance)

2.138089935299395


In [84]:
#problem 12

a = np.array ([2,3,4])

b = np.array([1,1,1])

p = np.array([[3], [5], [7]])

c = np.cross(a,b)

A =c[0]

denom = np.vdot(c,p)

distance = 6**(1/2)

D = ((np.linalg.norm(c))*distance) - denom

print(D)

print(A)


5.999999999999999
-1


In [71]:
#problem 13 

a = np.array([[2,1,1], [2,4,2], [3,3,3]])

b = np.array([5,12,12])

print(np.linalg.solve(a, b))

[1. 2. 1.]


In [60]:
#problem 14

a = np.array([[1,3,5], [6,2,3], [2,1,0]])

b = np.array([[0,3,5,1], [1,1,2,6], [2,3,2,0]])
         
print(np.matmul(a,b))

[[13 21 21 19]
 [ 8 29 40 18]
 [ 1  7 12  8]]


In [12]:
#problem 15 

A = [[1,1,1,1], [1,2,3,4], [4,3,2,1]]

A = Matrix(A)

A * A.nullspace()[0]

print(A.nullspace())

[Matrix([
[ 1],
[-2],
[ 1],
[ 0]]), Matrix([
[ 2],
[-3],
[ 0],
[ 1]])]


In [33]:
#problem 16

a = np.matrix([[-4,1,-1], [-4,-5,-3], [2,0,0]])

print(np.linalg.inv(a))

[[ 2.77555756e-17 -0.00000000e+00  5.00000000e-01]
 [ 3.75000000e-01 -1.25000000e-01  5.00000000e-01]
 [-6.25000000e-01 -1.25000000e-01 -1.50000000e+00]]


In [37]:
#problem 17

a = np.matrix([[-1,2], [4, -10]])

b = np.matrix([[-3], [14]])

print(np.linalg.solve(a,b))

[[ 1.]
 [-1.]]


In [32]:
#problem 18

a = np.matrix([[4,2], [-6,6]])

b = np.matrix([[14], [6]])

c = np.linalg.solve(a,b)

print(c)


[[2.]
 [3.]]


In [26]:
#problem 19

a = ([[2,4], [3,13]])

print(np.linalg.eig(a))

(array([ 1., 14.]), array([[-0.9701425 , -0.31622777],
       [ 0.24253563, -0.9486833 ]]))
